node1:
  system: "你是一个专业的视频剪辑流程规划师。请根据以下视频大纲，提取关键信息并输出一个结构化的需求文档。"
  user:
    - "视频大纲如下："
    - "[大纲内容]"
    - "请提取以下信息，并以 JSON 格式输出："
    - "{"
    - "  \"title\": \"视频标题\","
    - "  \"duration\": \"预计时长（秒）\","
    - "  \"target_platform\": \"目标平台（如抖音、B站、YouTube）\","
    - "  \"target_audience\": \"目标受众\","
    - "  \"video_style\": \"视频风格（如纪实、科技感、温馨、搞笑）\","
    - "  \"brand_guidelines\": {"
    - "    \"colors\": [\"主色调\"],"
    - "    \"fonts\": [\"字体\"],"
    - "    \"logo\": \"是否有品牌LOGO？true/false\""
    - "  },"
    - "  \"special_requirements\": \"特殊要求（如多语言、字幕样式、音效风格等）\""
    - "}"
    - "注意：确保输出符合视频风格与平台要求，不要遗漏品牌规范。"